---
- name: Install macOS packages
  hosts: all
  become: false
  vars:
    brew_tap_repos: []            # For empty list, use '[]'
      #- aws/tap                   # Provides: aws-sam-cli
    brew_cask_packages:
      - font-fira-code-nerd-font
      - font-hack-nerd-font
      - rar
      #- xquartz
      #- wireshark
    brew_packages:
      #- awscli
      #- aws-cdk
      #- aws-sam-cli               # Requires `aws/tap` tap
      - alacritty                 # Awesome terminal emulator
      - cmake                     # Needed to build `neovide`
      - colordiff                 # Seeing diff in color
      - cowsay
      - eza
      - go
      - htop
      - httpstat
      - jc                        # Serializes output of cli tools to structured JSON output
      - jq
      - mtr                       # ping+traceroute tool
      - neovim
      - nmap
      - nnn                       # command-line file browser
      - ripgrep
      - rustup-init               # Tool used to install rust compiler
      - sqlx-cli                  # command line for Rust sqlx
      - tmux
      - tree

  tasks:
    - import_tasks: tasks/homebrew.yml
